In [1]:
for i in range(4):
    for j in range(4):
        if j > i:
            break
        print ((i, j))
        
# Comments

(0, 0)
(1, 0)
(1, 1)
(2, 0)
(2, 1)
(2, 2)
(3, 0)
(3, 1)
(3, 2)
(3, 3)


In [4]:
for i in range(4):
    print (i)

0
1
2
3


In [7]:
x = 256
total = 0
while x>0:
    if total > 500:
        break
    total += x
    x = x//2
    print ("total:", total)
    print ("x:", x)

total: 256
x: 128
total: 384
x: 64
total: 448
x: 32
total: 480
x: 16
total: 496
x: 8
total: 504
x: 4


## Compare "append" and "extend" 

In [23]:
all_data = [['Joheeeen', 'Emeeeeily', 'Michael', 
             'Mary', 'Steven'],
            ['Maria', 'Emily', 'Javier', 
             'Natalia', 'Pilar']]
names_of_interest = []

for names in all_data:
    enough_es = [name for name in names if name.count('e')>2]
    names_of_interest.append(enough_es)

In [25]:
names_of_interest

[['Joheeeen', 'Emeeeeily'], []]

In [27]:
all_data = [['Joheeeen', 'Emeeeeily', 'Michael', 
             'Mary', 'Steven'],
            ['Maria', 'Emily', 'Javier', 
             'Natalia', 'Pilar']]
names_of_interest = []

for names in all_data:
    enough_es = [name for name in names if name.count('e')>2]
    names_of_interest.extend(enough_es)

In [28]:
# As we can see, the main difference between 
names_of_interest

['Joheeeen', 'Emeeeeily']

## Handle errors and exceptions gracefully

In [43]:
# Convert this x into float, so if x is the number related string then 
# we can do it, but if it's pure word-related strings then no.
def attempt_float_value(x):
    try:
        return float(x)
#         print ("This is a float: ", x)
    except ValueError:
        print ("I am suppressing the ValueError, but still gotta say that This is not a float! ")
        return x

In [44]:
attempt_float_value(1.6)

1.6

In [45]:
# This is a ValueError:
attempt_float_value("test")

I am suppressing the ValueError, but still gotta say that This is not a float! 


'test'

In [61]:
def attempt_float_type_and_value(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        print ("I am suppressing the error, but still gotta say that This is not a float! ", x)
        return x

In [52]:
attempt_float_type_and_value("test")

I am suppressing the error, but still gotta say that This is not a float!  test


'test'

In [53]:
attempt_float_type_and_value(['1'])

I am suppressing the error, but still gotta say that This is not a float!  ['1']


['1']

### Use of finally

In [59]:
# Let's execute whether the try gets blocked or not

x = "Still execute"
try:
    float(x)
finally:
    print (x)

Still execute


ValueError: could not convert string to float: 'Still execute'

In [74]:
# Original standard version will look like this:

x = "Test words"

# 1. Normally will want to execute this,
try:
    float(x)
# 2. If the error happens, what will this block of code do:
except:
    print ("Error! Cannot convert")
# 3. 
else:
    print ("No error! The converted float is: ", x)

Error! Cannot convert


In [67]:
try:
    fh = open("testfile", "w")
    fh.write("这是一个测试文件，用于测试异常!!")
except IOError:
    print("Error: 没有找到文件或读取文件失败")
else:
    print("内容写入文件成功")
    fh.close()

内容写入文件成功


In [79]:
# We can diretly run the py code using the %run magic function.
%run /Users/miaoyuesun/Code_Workspace/brad_public_workspace_mac/alphalens/alphalens/10_20_testing_run_code.py

Testing - Using magic run to run code.


## Files and the Operating System

In [89]:
path = "/Users/miaoyuesun/Code_Workspace/brad_public_workspace_mac/alphalens/alphalens/10_20_testing_run_code.txt"

### Method 1 of opening files: use "open"

In [90]:
f = open(path)

In [91]:
print (f)

<_io.TextIOWrapper name='/Users/miaoyuesun/Code_Workspace/brad_public_workspace_mac/alphalens/alphalens/10_20_testing_run_code.txt' mode='r' encoding='UTF-8'>


In [92]:
for line in f:
    print(line)

Testing - Using magic run to run code.

“Test line 2”

“Test line 3”

“Test line 4”

“Test line 5”


In [93]:
# If we use 'open' function to open the file, then we will need to 
# close it explicitly.
f.close()

### Method 2 of opening files: use "with"

In [94]:
# This diff is that with will automatically close the file without using
# f.close
with open(path) as f:
    lines = [x.rstrip() for x in f]

In [95]:
lines

['Testing - Using magic run to run code.',
 '“Test line 2”',
 '“Test line 3”',
 '“Test line 4”',
 '“Test line 5”']

### Write text to a file

In [96]:
with open('tmp.txt', 'w') as handle:
    handle.writelines(x for x in open(path) if len(x) > 1)

In [98]:
with open('tmp.txt', 'w') as handle:
    # Here x means all words in each row as the 
    # iteration goes
    handle.writelines(x for x in open(path))
    for x in open(path):
        print (len(x))

39
14
14
14
13


In [100]:
# This code shows where there's a new line, 
# indicated by \n
with open('tmp.txt') as f:
    lines = f.readlines()

In [101]:
lines

['Testing - Using magic run to run code.\n',
 '“Test line 2”\n',
 '“Test line 3”\n',
 '“Test line 4”\n',
 '“Test line 5”']

In [104]:
with open("tmp.txt", 'rb') as f:
    data = f.read()
data

b'Testing - Using magic run to run code.\n\xe2\x80\x9cTest line 2\xe2\x80\x9d\n\xe2\x80\x9cTest line 3\xe2\x80\x9d\n\xe2\x80\x9cTest line 4\xe2\x80\x9d\n\xe2\x80\x9cTest line 5\xe2\x80\x9d'

In [105]:
# Decode the bytes to the string object
data.decode("utf8")

'Testing - Using magic run to run code.\n“Test line 2”\n“Test line 3”\n“Test line 4”\n“Test line 5”'

# Chapter 4. NumPy Basics: Arrays and Vectorized Computation

In [106]:
import numpy as np

In [107]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [108]:
%time for _ in range(10): my_arr2 = my_arr*2

CPU times: user 13.3 ms, sys: 6.55 ms, total: 19.8 ms
Wall time: 19.3 ms


In [109]:
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: user 579 ms, sys: 175 ms, total: 754 ms
Wall time: 796 ms


In [116]:
%time my_arr2 = my_arr*2

CPU times: user 3.43 ms, sys: 3.92 ms, total: 7.35 ms
Wall time: 6.01 ms


In [126]:
%time my_list2 = [x*2 for x in my_list]

CPU times: user 73.9 ms, sys: 21.4 ms, total: 95.3 ms
Wall time: 98.4 ms


In [122]:
13.3/3.43

3.877551020408163

In [118]:
579/71.7

8.07531380753138

In [129]:
np.random.randn(2, 2)

array([[-0.09217723, -0.59648267],
       [ 1.01098495,  1.33522311]])

In [132]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [138]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [137]:
np.empty((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])